version: "2"

reviews:
  enabled: true
  auto_review:
    enabled: true
    base_branches:
      - "dev"

path_filters:
  - "!dev"
  - "!staging"
  - "!production"

review_profile: assertive

chat:
  auto_reply: true
